apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "metagpu.fullname" . }}
  labels:
    {{- include "metagpu.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ include "metagpu.fullname" . }}
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metagpu.fullname" . }}
  labels:
    {{- include "metagpu.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "metagpu.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metagpu.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}